### ISSUE TITLE
Can't set minVal and maxVal at the same time

### ISSUE THREAD

**Issue by bloemy7** [vermont42/JFADoubleSlider#11]
Hi,

JFADoubleSlider is absolutely awesome, thanks a lot.

One little thing: if you try to set the curMinVal and the curMaxVal one after the other, only the first one will be updated (using the [self setCurMinVal] and [self setCurMaxVal]).

To help this, I simply created another method: setCurMinValAndMaxVal. I copied the content of setCurMinVal and setCurMaxVal in it and it works.

It would be great to add this for everyone!

Thanks

**Comment by vermont42** [comment]
Happy to hear you find JFADoubleSlider useful. May I ask how you came across it?

Go ahead and submit a pull request. I am likely to accept it.

**Comment by bloemy7** [comment]
Hi,

I found in by using Google. I was looking for a solution for a DoubleSlider and yours came up!

I'm fairly new to Github and everything, and I'm not sure how to make a pull request. What is the way to go?

Thanks!

**Comment by vermont42** [comment]
Here is a good tutorial: https://github.com/CPAN-PRC/resources/wiki/My-first-Pull-Request

Here are detailed instructions:
Fork my repo on Github.
Clone your fork to your Mac using The Terminal. I believe that the command would be:
`git clone https://YBthebest@github.com/YBthebest/JFADoubleSlider.git`
Overwrite the files in the fork that you changed (likely JFADoubleSlider.h and JFADoubleSlider.m) with the changed files. From the root of the cloned folder, execute the following command, which should tell you that there are two modified files, assuming that my guess is correct.
`git status`
Assuming that there are two (or the appropriate number of) files:
`git add .`
`git commit -m "add setCurMinValAndMaxVal method"`
`git push origin`
Then follow the instructions in the tutorial for submitting the pull request.
If you have any questions, feel free to email me at vermontcoder at gmail dot com. Replace " at " and " dot " with "@" and ".", respectively.

**Comment by bloemy7** [comment]
Hi,

thanks a lot! I followed all the steps. but I get this message when I try to push to the origin:

remote: Permission to vermont42/JFADoubleSlider.git denied to YBthebest.
fatal: unable to access 'https://github.com/vermont42/JFADoubleSlider.git/': The requested URL returned error: 403

My password is definitely correct. Any reason this could be happening?

**Comment by vermont42** [comment]
Assuming that you cloned the correct repo to your Mac (the command should be `git clone https://YBthebest@github.com/YBthebest/JFADoubleSlider.git`, not `git clone https://YBthebest@github.com/vermont42/JFADoubleSlider.git`), you may need to make a new branch, push that, and pull request that. From the command line:
`git checkout -b bugfix`
`git push origin bugfix`
Github will then allow you to pull request the `bugfix` branch.
If this doesn't work, I would be happy to troubleshoot via Screenhero, a free app you can download.

**Comment by bloemy7** [comment]
The point is that with this command:
git clone https://YBthebest@github.com/YBthebest/JFADoubleSlider.git

I get a Fatal error: repository not found.

With your username instead of mine after the .com/, I am able to copy it correctly. How can I change that?

Thanks a lot for the work, we'll figure it out ;-)

**Comment by vermont42** [comment]
I see this error when I attempt to clone a repo that does not exist.

I don't see your repo on your Github page, perhaps because it is private. Try making it public. After you do so, I will attempt to clone it.

One possibility is that you have not stored your Github password in your keychain. If that is the case, [this](https://help.github.com/articles/caching-your-github-password-in-git/) will help.

**Comment by bloemy7** [comment]
Hi,

but the repo is not on my GitHub page. I think this is the point I'm missing -- how should I proceed from the very beginning to have the repo on my page?

Thanks !

**Comment by vermont42** [comment]
Click the Fork button in the top right corner.

**Comment by vermont42** [comment]
Here are instructions from GitHub: https://help.github.com/articles/fork-a-repo/

**Comment by bloemy7** [comment]
Thanks for the help! Sorry, I was on holidays, I got it done ;)

**Comment by vermont42** [comment]
I tried to reproduce the bug and could not. To reproduce the bug, I added a button to the sample app to trigger the following method:

``` objective-c
- (IBAction)setBoth {
    self.programmaticSlider.curMinVal = -400.0;
    self.programmaticSlider.curMaxVal = 400.0;
    self.iBDoubleSlider.curMinVal = -1.0;
    self.iBDoubleSlider.curMaxVal = 1.0;
}
```

This code correctly set the current min and max values of the programmatic and IB double sliders.

Can you give me more context for how you were trying to set the current min and max values and what was happening?

**Comment by bloemy7** [comment]
Hi,

that is weird. I am using it in the viewDidLoad method, in a simple ViewController. I have an IBDoubleSlider.

```
[self.doubleSlider setCurMinVal:25.0];
[self.doubleSlider setCurMaxVal:69.0];
```

Would result in this bug. Whichever one I would put first would work -- the second one not.

**Comment by vermont42** [comment]
Thanks for the pull request.
